run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/M-Yamashita01/cloudflare-mcp-go

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
